#!/bin/bash

# --------------------------------------------------------------------
# Author: 23884895 - Xuechen MAO
# Purpose: The script is used to count the number of empty cells in each column of a file, and the separator is provided as a second argument
# Usage: ./empty_cells input_file.txt seperator, e.g. ./empty_cells file.txt ';'
# --------------------------------------------------------------------

# accept 2 arguments: input file and separator
file="$1"
separator="$2"

# 1. Check number of arguments, and print usage if not 2
if [ $# -ne 2 ]; then
    echo "Usage: ./empty_cells input_file.txt seperator" >&2
    exit 1
fi

# 2. Check if the first input - file exists
if [ ! -f "$file" ]; then
    echo "Error: File '$file' does not exist." >&2
    exit 1
fi

# 3. using header to check if the separator actually appears
if [[ ! $(head -n 1 "$file") =~ "$separator" ]]; then
    echo "Error: Separator '$separator' not found in the file." >&2
    exit 1
fi

awk -F"$separator" '
# process the 1st row -- header, and initialize the number to 0
NR == 1 {
    sub(/\r$/, "")  # remove carriage return if present
    for (i = 1; i <= NF; i++) {
        headers[i] = $i
        count[i] = 0
    }
    next
}

{
    sub(/\r$/, "")  # remove carriage return from each data line
    for (i = 1; i <= NF; i++) {
        if ($i == "") {
            count[i]++
        }
    }
}

END {
    for (i = 1; i <= length(headers); i++) {
        print headers[i] ": " count[i]
    }
}
' "$file"
