#!/bin/bash

# 23884895 - Xuechen MAO
# The script is used to count the number of empty cells in each column of a txt file

# add first input as file
file=$1

# if no valid file, print error and exit
if [ $# -ne 1 ]; then
    echo "error: file does not exist. Please use a valid file" >&2 
    exit 1
fi


awk -F';' '
# process the 1st row -- header, and initialize the number to 0
NR == 1 {
    sub(/\r$/, "")  # remove carriage return if present
    for (i = 1; i <= NF; i++) {
        headers[i] = $i
        count[i] = 0
    }
    next
}

{
    sub(/\r$/, "")  # remove carriage return from each data line
    for (i = 1; i <= NF; i++) {
        if ($i == "") {
            count[i]++
        }
    }
}

END {
    for (i = 1; i <= length(headers); i++) {
        print headers[i] ": " count[i]
    }
}
' "$file"
