#!/bin/bash

file=$1

# Check for exactly one input file
if [ $# -ne 1 ]; then
    echo "Usage: $0 input_file" >&2
    exit 1
fi

# Get the max ID and set next_id to fill in empty id
max_id=$(awk -F';' 'NR > 1 { if ($1 > max) max = $1 } END { print max }' "$file")
next_id=$((max_id + 1))

# 1. clean /r/n to /n
# 2. fill in with max_id+1
# 3. transform , into .
# 4. delete non-ASCII
# 5. transform ; into \t
